# Generated by Django 3.1.6 on 2021-02-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinrequest',
            name='slug',
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
