# Generated by Django 3.1.6 on 2021-02-15 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0003_auto_20210215_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='members',
            field=models.ManyToManyField(null=True, related_name='belong_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
