# Generated by Django 3.1.6 on 2021-02-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='is_activated',
            field=models.BooleanField(default=None, null=True, verbose_name='Activated'),
        ),
    ]
