# Generated by Django 3.1.6 on 2021-02-16 06:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0005_joinrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='members',
            field=models.ManyToManyField(related_name='belong_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
