# Generated by Django 3.1.6 on 2021-02-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0008_organisation_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='thumb',
            field=models.ImageField(blank='true', default='default.png', upload_to=''),
        ),
    ]
