# Generated by Django 3.1.6 on 2021-02-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0009_organisation_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='thumb',
            field=models.ImageField(blank='true', default='default.jpeg', upload_to=''),
        ),
    ]
