# Generated by Django 3.1.6 on 2021-02-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0011_auto_20210221_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='thumb',
            field=models.ImageField(blank='true', default='default.jpg', upload_to=''),
        ),
    ]
